# Generated by Django 4.1.3 on 2022-11-01 20:04

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaletOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Chalet Name')),
                ('location', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SelectChalet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('capacity', models.TextField()),
                ('selected_date', models.DateField()),
                ('chalet_images', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Image')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chalet_location', to='my_chalet_site.chaletoption')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choose_chalet', to='my_chalet_site.chaletoption')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chalet_price', to='my_chalet_site.chaletoption')),
                ('request_reservation', models.ManyToManyField(blank=True, related_name='send_interest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
