# Generated by Django 4.1.3 on 2022-11-21 14:19

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_chalet_site.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaletList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Chalet Name')),
                ('location', models.CharField(default='location', max_length=150)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Image')),
                ('description', models.TextField(default='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('chalet_images', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='MakeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150, null=True, verbose_name='First Name')),
                ('lname', models.CharField(max_length=150, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('capacity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='2', max_length=2)),
                ('date', models.DateField(default=datetime.datetime(2022, 11, 22, 14, 18, 59, 658087, tzinfo=datetime.timezone.utc), validators=[my_chalet_site.models.MakeReservation.validation])),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
