# Generated by Django 4.1.3 on 2022-11-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chalet_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makereservation',
            name='fname',
            field=models.CharField(max_length=150, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='makereservation',
            name='lname',
            field=models.CharField(max_length=150, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='makereservation',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
