# Generated by Django 4.1.3 on 2022-11-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_chalet_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChaletOption',
            new_name='ChaletList',
        ),
    ]
