# Generated by Django 4.1.3 on 2022-11-21 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chalet_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makereservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 20, 12, 52, 738884)),
        ),
    ]
