# Generated by Django 4.1.3 on 2022-11-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chalet_site', '0002_rename_chaletoption_chaletlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaletlist',
            name='location',
            field=models.CharField(default='location', max_length=150),
        ),
        migrations.AlterField(
            model_name='selectchalet',
            name='capacity',
            field=models.TextField(default='capacity'),
        ),
        migrations.AlterField(
            model_name='selectchalet',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='selectchalet',
            name='location',
            field=models.CharField(default='location', max_length=150),
        ),
        migrations.AlterField(
            model_name='selectchalet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
