# Generated by Django 4.1.3 on 2022-11-23 19:23

from django.db import migrations, models
import django.db.models.deletion
import my_chalet_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chalet_site', '0003_alter_makereservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='makereservation',
            name='selected_chalet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_chalet_site.chaletlist'),
        ),
        migrations.AlterField(
            model_name='makereservation',
            name='date',
            field=models.DateField(default=my_chalet_site.models.MakeReservation.date_tomorrow, validators=[my_chalet_site.models.MakeReservation.validation]),
        ),
    ]
