# Generated by Django 4.1.3 on 2022-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chalet_site', '0004_makereservation_selected_chalet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makereservation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
