# Generated by Django 4.1.3 on 2022-12-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_chalet_site', '0005_alter_makereservation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaletlist',
            name='chalet_images',
        ),
    ]
