# Generated by Django 4.1.3 on 2022-12-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chalet_site', '0006_remove_chaletlist_chalet_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaletlist',
            name='location_url',
            field=models.CharField(default='location', max_length=150),
        ),
    ]
