# Generated by Django 4.1.3 on 2022-12-22 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_chalet_site', '0007_chaletlist_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makereservation',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='Phone Number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='makereservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
