# Generated by Django 4.1.3 on 2022-12-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chalet_site', '0008_alter_makereservation_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makereservation',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
