# Generated by Django 4.1.3 on 2022-12-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chalet_site', '0010_alter_makereservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makereservation',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
