# Generated by Django 4.1.3 on 2022-12-23 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chalet_site', '0011_alter_makereservation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makereservation',
            name='phone',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
